import type { Metadata } from 'next';
import { domine, lora } from './fonts';
import '../shared/styles/globals.css';
import { AppSidebar } from '@/components/layouts';
import { Header } from '@/components/layouts/Header';
import { SidebarProvider, SidebarInset } from '@/components/ui/sidebar';
import { Toaster } from '@/components/ui/sonner';
import { db } from '@/db';
import { posts } from '@/db/schema/post';
import { ThemeProvider } from '@/providers';

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

export const metadata: Metadata = {
  title: 'HighTechRoller',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const allPosts = await db.select({ tags: posts.tags }).from(posts);
  const tagCounts: Record<string, number> = {};
  allPosts.forEach((post) => {
    post.tags.forEach((tag) => {
      tagCounts[tag] = (tagCounts[tag] || 0) + 1;
    });
  });

  return (
    <html lang='en' className={`${domine.variable} ${lora.variable}`} suppressHydrationWarning>
      <body className={`antialiased`}>
        <ThemeProvider attribute='class' defaultTheme='dark' enableSystem disableTransitionOnChange>
          <SidebarProvider>
            <AppSidebar tagCounts={tagCounts} />
            <SidebarInset>
              <Header />
              <main>{children}</main>
              <Toaster />
            </SidebarInset>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
